services:
  postgres_db:
    image: postgres:latest
    container_name: db_postgres_snowball_bot
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.dbenvironment
  bot:
    build: .
    container_name: snowball_bot
    command: python ./run.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db