services:
  postgres_db:
    image: postgres:latest
    container_name: db_postgres_snowball_bot
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=snowball_bot
  bot:
    build: .
    container_name: snowball_bot
    command: python ./run.py --create_db
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db