networks:
  valentin:
    name: valentin
    external: true

services:
  valentin-bot-db:
    image: postgres:latest
    container_name: valentin-bot-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=valentin_bot_db
    networks:
      - valentin
  valentin-bot:
    build: .
    container_name: valentin-bot
    command: python ./run.py --create_db
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - valentin
    depends_on:
      - valentin-bot-db