name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Droplet
        run: |
          sshpass -p "${{ secrets.DO_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }} << 'EOF'
          cd snowball/
          git pull origin main
          docker compose down
          docker compose up -d --build snowball_bot
          docker compose up -d db_postgres_snowball_bot
          docker exec snowball_bot python3 create_tables.py
          EOF
